<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Confirmation</title>
</head>
<body>
<h1 style="color: green">Registration Confirmation / Подтверждение регистрации</h1>
<h2>Welcome, / Добрый день, ${name}!</h2>
<p> Please confirm your email address by clicking the link below / </p>
<p> Для подтверждения регистрации пройдите по <a href="${link}">ссылке</a></p>
<p>This link will expire in 24 hours.</p>
<hr style="border: 1px solid #eee; margin: 20px 0;">

        <p style="font-size: 12px; color: #999;">
            If you didn't register for this account, please ignore this email.
        </p>
</body>
</html>